// src/index.react.tsx
/* @refresh reload */
import React from 'react';
import ReactDOM from 'react-dom/client';

import './index.css';
import { MyReactApp } from './App.react';

// Render React
const rootReact = document.getElementById('root-react');

if (import.meta.env.DEV && !(rootReact instanceof HTMLElement)) {
  throw new Error(
    'Root element for React not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?'
  );
}

ReactDOM.createRoot(rootReact!).render(<MyReactApp />);

// src/index.solid.tsx
/** @jsxImportSource solid-js */
/* @refresh reload */
import { render } from "solid-js/web";

import "./index.css";
import { MySolidApp } from "./App.solid";

// Render Solid
const rootSolid = document.getElementById("root-solid");

if (import.meta.env.DEV && !(rootSolid instanceof HTMLElement)) {
  throw new Error(
    "Root element for SolidJS not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?"
  );
}

render(() => <MySolidApp />, rootSolid!);
